export const MOCK_PARKINGS = [
  {
    id: '1',
    name: 'Cityparken',
    address: 'Kungsgatan 10, Stockholm',
    lat: 59.3346,
    lng: 18.0632,
    pricePerHour: 0,
    isFree: true,
    maxHours: null,
    description: 'Free street parking',
  },
  {
    id: '2',
    name: 'P-hus Norrmalm',
    address: 'Sveavägen 44, Stockholm',
    lat: 59.3370,
    lng: 18.0592,
    pricePerHour: 35,
    isFree: false,
    maxHours: null,
    description: 'Indoor parking garage',
  },
  {
    id: '3',
    name: 'Stureplan Parkering',
    address: 'Stureplan 2, Stockholm',
    lat: 59.3355,
    lng: 18.0726,
    pricePerHour: 50,
    isFree: false,
    maxHours: 4,
    description: 'Max 4 hours',
  },
  {
    id: '4',
    name: 'Gamla Stan Fri',
    address: 'Västerlånggatan 5, Stockholm',
    lat: 59.3240,
    lng: 18.0710,
    pricePerHour: 0,
    isFree: true,
    maxHours: 2,
    description: 'Free max 2 hours',
  },
  {
    id: '5',
    name: 'Södermalm P',
    address: 'Götgatan 30, Stockholm',
    lat: 59.3160,
    lng: 18.0710,
    pricePerHour: 25,
    isFree: false,
    maxHours: null,
    description: 'Street parking',
  },
];
